/**
 * Central icon re-exports — import all Polaris icons from here.
 * Vite tree-shakes unused icons, so bundle size stays optimal.
 *
 * Usage: import { ProductIcon, SearchIcon } from "../lib/icons";
 *
 * When adding a new icon, add it here FIRST so it's available everywhere.
 */
export {
  AlertCircleIcon,
  AlertDiamondIcon,
  AlertTriangleIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  AutomationIcon,
  BookOpenIcon,
  CartIcon,
  CashDollarIcon,
  CategoriesIcon,
  ChartVerticalFilledIcon,
  ChartVerticalIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSmallIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CodeIcon,
  CollectionFilledIcon,
  CollectionIcon,
  ConnectIcon,
  DatabaseIcon,
  DeleteIcon,
  EditIcon,
  EmailIcon,
  ExportIcon,
  ExternalIcon,
  FileIcon,
  FilterIcon,
  FlagIcon,
  GlobeIcon,
  HashtagIcon,
  ImportIcon,
  InfoIcon,
  LinkIcon,
  ListBulletedIcon,
  LockIcon,
  NotificationIcon,
  OrderIcon,
  PackageIcon,
  PageIcon,
  PersonIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  ProductIcon,
  QuestionCircleIcon,
  RefreshIcon,
  SearchIcon,
  SettingsIcon,
  StarFilledIcon,
  StopCircleIcon,
  TargetIcon,
  ViewIcon,
  WandIcon,
} from "@shopify/polaris-icons";
